In [2]:
import tensorflow as tf
tens1 = tf.constant([[[1,2],[2,3]],[[3,4],[5,6]]])
sess = tf.Session()
print(sess.run(tens1)[1,1,0])

5


In [4]:
import tensorflow as tf
import numpy as np
x = tf.constant(np.random.rand(32).astype(np.float32))
y = tf.constant([1,2,3])
sess = tf.Session()
print(sess.run(x))
print(sess.run(y))

[  4.74571437e-01   7.60025322e-01   1.05701625e-01   2.88277268e-01
   2.22559497e-02   4.39066023e-01   7.22795069e-01   8.26475978e-01
   1.15051016e-01   3.61691564e-01   2.51560807e-01   1.36525586e-01
   4.28789288e-01   7.86597550e-01   4.93674546e-01   4.73415537e-04
   2.96432018e-01   7.25581586e-01   1.16520487e-01   1.71344295e-01
   2.62603253e-01   3.33728760e-01   1.99599579e-01   5.46050429e-01
   2.72815704e-01   2.61270970e-01   4.03398544e-01   7.00995743e-01
   9.55806017e-01   1.71963603e-03   7.25019753e-01   3.23337644e-01]
[1 2 3]


In [8]:
import tensorflow as tf
import numpy as np
sess = tf.Session()
x_data = np.array([[1,2,3], [3,2,6]])
x = tf.convert_to_tensor(x_data,dtype=tf.float32)
print(x)

Tensor("Const_9:0", shape=(2, 3), dtype=float32)


In [10]:
# Build a data flow graph

import tensorflow as tf
g = tf.Graph()
with g.as_default():
    #import tensorflow as tf
    sess = tf.Session()
    W_m = tf.Variable(tf.zeros([10,5]))
    x_v = tf.placeholder(tf.float32,[None,10])
    result = tf.matmul(x_v,W_m)
    print(g.as_graph_def())

node {
  name: "zeros"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
          dim {
            size: 10
          }
          dim {
            size: 5
          }
        }
        float_val: 0.0
      }
    }
  }
}
node {
  name: "Variable"
  op: "VariableV2"
  attr {
    key: "container"
    value {
      s: ""
    }
  }
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 10
        }
        dim {
          size: 5
        }
      }
    }
  }
  attr {
    key: "shared_name"
    value {
      s: ""
    }
  }
}
node {
  name: "Variable/Assign"
  op: "Assign"
  input: "Variable"
  input: "zeros"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "_class"
    value {
      list {
        s: "loc:@Variable"
      }
    }


In [14]:
# Matrix operations
import tensorflow as tf
sess = tf.InteractiveSession()
x = tf.constant([[2,5,3,-5],
                [0,3,-2,5],
                [4,3,5,3],
                [6,1,4,0]])
y = tf.constant([[4,-7,4,-3,4],
                [6,4,-7,4,7],
                [2,3,2,1,4],
                [1,5,5,5,2]])
floatx = tf.constant([[2.,5.,3.,-5.],
                     [0.,3.,-2.,5.],
                     [4.,3.,5.,3.],
                     [6.,1.,4.,0.]])
tf.transpose(x).eval()

array([[ 2,  0,  4,  6],
       [ 5,  3,  3,  1],
       [ 3, -2,  5,  4],
       [-5,  5,  3,  0]], dtype=int32)

In [12]:
# Matrix multiplication
tf.matmul(x,y).eval()

array([[ 39, -10, -46,  -8,  45],
       [ 19,  31,   0,  35,  23],
       [ 47,  14,  20,  20,  63],
       [ 38, -26,  25, -10,  47]], dtype=int32)

In [15]:
# Matrix determinant
tf.matrix_determinant(floatx).eval()

818.0

In [16]:
# Matrix inverse
tf.matrix_inverse(floatx).eval()

array([[-0.00855745,  0.10513447, -0.18948655,  0.29584354],
       [ 0.12958434,  0.12224938,  0.01222495, -0.05134475],
       [-0.01955992, -0.18826404,  0.28117359, -0.18092909],
       [-0.08557458,  0.05134474,  0.10513448, -0.0415648 ]], dtype=float32)

In [17]:
# solve matrix system
tf.matrix_solve(floatx, [[1],[1],[1],[1]]).eval()

array([[ 0.202934  ],
       [ 0.21271393],
       [-0.10757945],
       [ 0.02933985]], dtype=float32)

In [18]:
import tensorflow as tf
sess = tf.InteractiveSession()
x = tf.constant([[1,2,3],
                [3,2,1],
                [-1,-2,-3]])
boolean_tensor = tf.constant([[True, False, True],
                             [False, False, True],
                             [True, False, False]])
tf.reduce_prod(x, reduction_indices=1).eval()

array([ 6,  6, -6], dtype=int32)

In [19]:
tf.reduce_min(x, reduction_indices=1).eval()

array([ 1,  1, -3], dtype=int32)

In [20]:
tf.reduce_max(x, reduction_indices=1).eval()

array([ 3,  3, -1], dtype=int32)

In [22]:
tf.reduce_mean(x, reduction_indices=1).eval()

array([ 2,  2, -2], dtype=int32)

In [23]:
tf.reduce_all(boolean_tensor, reduction_indices=1).eval()

array([False, False, False], dtype=bool)

In [25]:
tf.reduce_any(boolean_tensor, reduction_indices=1).eval()

array([ True,  True,  True], dtype=bool)

In [28]:
# Tensor segmentation, a process in which one of the dimensions is reduced, and the resulting elements are determined 
# by an index row.

import tensorflow as tf
sess = tf.InteractiveSession()
seg_ids = tf.constant([0,1,1,2,2])
tens1 = tf.constant([[2,5,3,-5],
                     [0,3,-2,5],
                    [4,3,5,3],
                    [6,1,4,0],
                    [6,1,4,0]])
tf.segment_sum(tens1, seg_ids).eval()

array([[ 2,  5,  3, -5],
       [ 4,  6,  3,  8],
       [12,  2,  8,  0]], dtype=int32)

In [29]:
tf.segment_prod(tens1, seg_ids).eval()

array([[  2,   5,   3,  -5],
       [  0,   9, -10,  15],
       [ 36,   1,  16,   0]], dtype=int32)

In [30]:
tf.segment_min(tens1, seg_ids).eval()

array([[ 2,  5,  3, -5],
       [ 0,  3, -2,  3],
       [ 6,  1,  4,  0]], dtype=int32)

In [31]:
tf.segment_max(tens1, seg_ids).eval()

array([[ 2,  5,  3, -5],
       [ 4,  3,  5,  5],
       [ 6,  1,  4,  0]], dtype=int32)

In [32]:
tf.segment_mean(tens1, seg_ids).eval()

array([[ 2,  5,  3, -5],
       [ 2,  3,  1,  4],
       [ 6,  1,  4,  0]], dtype=int32)

In [33]:
# Sequences

import tensorflow as tf
sess = tf.InteractiveSession()
x = tf.constant([[2,5,3,-5],
                [0,3,-2,5],
                [4,3,5,3],
                [6,1,4,0]])
listx = tf.constant([1,2,3,4,5,6,7,8])
listy = tf.constant([4,5,8,9])
boolx = tf.constant([[True, False],[False, True]])
tf.argmin(x,1).eval()

array([3, 2, 1, 3])

In [34]:
tf.argmax(x,1).eval()

array([1, 3, 2, 0])

In [36]:
tf.setdiff1d(listx,listy)[0].eval()#setdiff1d is a rename of tf.listdiff

array([1, 2, 3, 6, 7], dtype=int32)

In [37]:
tf.where(boolx).eval()

array([[0, 0],
       [1, 1]])

In [38]:
tf.unique(listx)[0].eval()

array([1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)

In [39]:
# Tensor shape transformations

import tensorflow as tf
sess = tf.InteractiveSession()
x = tf.constant([[2,5,3,-5],
                [0,3,-2,5],
                [4,3,5,3],
                [6,1,4,0]])
tf.shape(x).eval() #shape of the tensor

array([4, 4], dtype=int32)

In [40]:
tf.size(x).eval() #size of the tensor

16

In [41]:
tf.reshape(x,[8,2]).eval() # converting to a 8*2 matrix

array([[ 2,  5],
       [ 3, -5],
       [ 0,  3],
       [-2,  5],
       [ 4,  3],
       [ 5,  3],
       [ 6,  1],
       [ 4,  0]], dtype=int32)

In [42]:
tf.squeeze(x).eval()

array([[ 2,  5,  3, -5],
       [ 0,  3, -2,  5],
       [ 4,  3,  5,  3],
       [ 6,  1,  4,  0]], dtype=int32)

In [43]:
tf.expand_dims(x,1).eval() # Expanding dims

array([[[ 2,  5,  3, -5]],

       [[ 0,  3, -2,  5]],

       [[ 4,  3,  5,  3]],

       [[ 6,  1,  4,  0]]], dtype=int32)

In [45]:
# Tensor slicing and joining

import tensorflow as tf
sess = tf.InteractiveSession()
t_matrix = tf.constant([[1,2,3],
                       [4,5,6],
                       [7,8,9]])
t_array = tf.constant([1,2,3,4,5,2,3,9])
t_array2 = tf.constant([2,3,4,2,8,5,6,7])
tf.slice(t_matrix, [1,1],[2,2]).eval()

array([[5, 6],
       [8, 9]], dtype=int32)

In [47]:
tf.tile([1,2],[3]).eval()

array([1, 2, 1, 2, 1, 2], dtype=int32)

In [48]:
tf.pad(t_matrix, [[0,1],[2,1]]).eval()

array([[0, 0, 1, 2, 3, 0],
       [0, 0, 4, 5, 6, 0],
       [0, 0, 7, 8, 9, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int32)